Remove glance proxypass kuttl tests
Glance standalone is no longer supported.
"""
Running command: '/usr/bin/glance-api --config-dir /etc/glance/glance.conf.d'
+ umask 0022
+ exec /usr/bin/glance-api --config-dir /etc/glance/glance.conf.d
ERROR: Standalone glance-api is no longer supported. Deploy Glance under a WSGI server using glance.wsgi.api:application.
"""

Removing kuttl tests and just keep the code for a potential transition
from 18 to 19.

Signed-off-by: Francesco Pantano <fpantano@redhat.com>